# from https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md
version: "3"

services:
  sonarqube:
    image: sonarqube
#    command: -Dsonar.ce.javaOpts=-Xmx512m -Dsonar.web.javaOpts=-Xmx512m
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./volumes/sonarqube_conf:/opt/sonarqube/conf
      - ./volumes/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonarqube_extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./volumes/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
    internal: false
